---
- name: Filbeat Installation Playbook
  hosts: webservers
  become: yes
  tasks:

    - name: Download .deb file from artifacts.elastic.co
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

    - name: Install .deb file using dpkg command
      command: dpkg -i filebeat-7.4.0-amd64.deb

    - name: Copy Filebeat configuration from Ansible
      copy:
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Enable filebeat modules
      command: filebeat modules enable system

    - name: Set filebeat
      command: filebeat setup

    - name: Start filebeat
      command: service filebeat start

    - name: Enable filebeat on boot
      systemd:
        name: filebeat
        enabled: yes
